spring:
  application:
    name: sql-garble-spring-boot-sample
  datasource:
    #设置北京时间以及调整数据时间和写入数据库的文字编码类型
    url: jdbc:mysql://localhost:3306?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    #引擎
    driver-class-name: com.mysql.cj.jdbc.Driver

garble:
  valid: true
  garble-function-list:
    - 1
  updated-data-msg:
    excluded-mapper-path:
      - "com.aster.mapper.ExcludeMapper"
    default-flag-col-name: "update_record"
    dealWithUpdatedPath: "com.baidu"
    monitored-table-map: { 'user_table': 'id', 'log_table': 'id' }


