spring:
  application:
    name: sql-garble-spring-boot-sample
garble:
  excluded-mapper-path:
    - "com.aster.mapper.ExcludeMapper"
  default-flag-col-name: "update_record"
  monitored-table-map: {'user_table': 'id', 'log_table': 'id'}
  garble-function-list:
    - 1
